lib/plate_slate_web/router.ex
defmodule PlateSlateWeb.Router do
  use PlateSlateWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PlateSlateWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug PlateSlateWeb.Context
  end

  pipeline :admin_auth do
    plug PlateSlateWeb.AdminAuth
  end

  scope "/" do
    pipe_through :api

    forward "/api", Absinthe.Plug, schema: PlateSlateWeb.Schema

    forward "/graphiql", Absinthe.Plug.GraphiQL,
      schema: PlateSlateWeb.Schema,
      socket: PlateSlateWeb.UserSocket
  end

  # Other scopes may use custom stacks.
  # scope "/api", PlateSlateWeb do
  #   pipe_through :api
  # end

  scope "/admin", PlateSlateWeb do
    pipe_through :browser

    resources "/session", SessionController,
      only: [:new, :create, :delete],
      singleton: true
  end

  scope "/admin", PlateSlateWeb do
    pipe_through [:browser, :admin_auth]

    resources "/items", ItemController
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PlateSlateWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/plate_slate/menu/item.ex
defmodule PlateSlate.Menu.Item do
  use Ecto.Schema
  import Ecto.Changeset
  alias PlateSlate.Menu.Item

  schema "items" do
    field :added_on, :date
    field :description, :string
    field :name, :string
    field :price, :decimal
    field :allergy_info, {:array, :map}

    belongs_to :category, PlateSlate.Menu.Category

    many_to_many :tags, PlateSlate.Menu.ItemTag, join_through: "items_taggings"

    timestamps()
  end

  @doc false
  def changeset(%Item{} = item, attrs) do
    item
    |> cast(attrs, [:name, :description, :price, :added_on])
    |> validate_required([:name, :price])
    |> foreign_key_constraint(:category)
    |> unique_constraint(:name)
  end
end

lib/plate_slate/ordering/item.ex
defmodule PlateSlate.Ordering.Item do
  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do
    field :price, :decimal
    field :name, :string
    field :quantity, :integer
  end

  def changeset(item, attrs) do
    item
    |> cast(attrs, [:price, :name, :quantity])
    |> validate_required([:price, :name, :quantity])
  end
end

lib/plate_slate_web/controllers/item_controller.ex
defmodule PlateSlateWeb.ItemController do
  use PlateSlateWeb, :controller

  use Absinthe.Phoenix.Controller,
    schema: PlateSlateWeb.Schema,
    action: [mode: :internal]

  @graphql """
  query {
    menu_items @put {
      category
      order_history {
        quantity
      }
    }
  }
  """
  def index(conn, result) do
    render(conn, "index.html", items: result.data.menu_items)
  end

  @graphql """
  query ($id: ID!, $since: Date) {
    menu_item(id: $id) @put {
      order_history(since: $since) {
        quantity
        gross
        orders
      }
    }
  }
  """
  def show(conn, %{data: %{menu_item: nil}}) do
    conn
    |> put_flash(:info, "Menu item not found")
    |> redirect(to: "/admin/items")
  end

  def show(conn, %{data: %{menu_item: item}}) do
    since = variables(conn)["since"] || "2018-01-01"
    render(conn, "show.html", item: item, since: since)
  end
end

lib/plate_slate_web/views/item_view.ex
defmodule PlateSlateWeb.ItemView do
  use PlateSlateWeb, :view
end

lib/plate_slate_web/templates/item/index.html.heex
<h2>Listing Items</h2>

<table class="table">
  <thead>
    <tr>
      <th>Menu Item</th>
      <th>Category</th>
      <th></th>
    </tr>
  </thead>
  <tbody>

<%= for item <- @items do %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.category.name %></td>
      <td class="text-right">
        <span><%= link "Show", to: Routes.item_path(@conn, :show, item),
          class: "btn btn-default btn-xs" %>
        </span>
        <span><%= link "Edit", to: Routes.item_path(@conn, :edit, item),
          class: "btn btn-default btn-xs" %>
        </span>
        <span><%= link "Delete", to: Routes.item_path(@conn, :delete, item),
          method: :delete,
          data: [confirm: "Are you sure?"],
          class: "btn btn-danger btn-xs" %>
        </span>
      </td>

    </tr>
<% end %>
  </tbody>
</table>

lib/plate_slate_web/templates/item/show.html.eex
<h2>
  <%= @item.name %>
</h2>

<%= form_tag Routes.item_path(@conn, :show, @item), method: :get do %>
  <div class="form-group">
    <label for="since">Since</label>
    <input type="date" id="since" name="since" value="<%= @since %>"/>
  </div>
  <%= submit "Filter Orders", class: "btn btn-primary" %>
<% end %>

<%= if Enum.empty?(@item.order_history.orders) do %>
  <p>No units have been sold during this time period.</p>
<% else %>
  <h3>
    Sold
    <%= @item.order_history.quantity %>
    ($<%= Decimal.round(@item.order_history.gross, 2) %> gross)
  </h3>
  <table class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Count</th>
      </tr>
    </thead>
    <tbody>
      <%= for order <- @item.order_history.orders do %>
      <tr>
        <td><%= order.ordered_at |> DateTime.to_date %></td>
        <td><%= order.items |> Enum.map(&(&1.quantity)) |> Enum.sum %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<p>
  <%= link "Back",
        to: Routes.item_path(@conn, :index),
        class: "btn btn-default btn-xs" %>
</p>